#include <iostream.h>
#include <conio.h>
#include <iomanip.h>
void main()
{
clrscr();
cout<<"    *"<<endl;
cout<<"   * *"<<endl;
cout<<"  *****"<<endl;
cout<<" *     *"<<endl;
cout<<"*       *"<<endl;
cout<<"\n"<<endl;
cout<<"******"<<endl;
cout<<"*     *"<<endl;
cout<<"*     *"<<endl;
cout<<"******"<<endl;
cout<<"*     *"<<endl;
cout<<"*     *"<<endl;
cout<<"******"<<endl;
cout<<"\n"<<endl;
cout<<"*******"<<endl;
cout<<"*"<<endl;
cout<<"*"<<endl;
cout<<"*"<<endl;
cout<<"*"<<endl;
cout<<"*******"<<endl;
cout<<"\n"<<endl;
cout<<"******"<<endl;
cout<<"*     *"<<endl;
cout<<"*     *"<<endl;
cout<<"*     *"<<endl;
cout<<"*     *"<<endl;
cout<<"*     *"<<endl;
cout<<"******"<<endl;
cout<<"\n"<<endl;
cout<<"******"<<endl;
cout<<"*"<<endl;
cout<<"*"<<endl;
cout<<"******"<<endl;
cout<<"*"<<endl;
cout<<"*"<<endl;
cout<<"******"<<endl;
cout<<"\n"<<endl;
cout<<"******"<<endl;
cout<<"*"<<endl;
cout<<"*"<<endl;
cout<<"******"<<endl;
cout<<"*"<<endl;
cout<<"*"<<endl;
cout<<"*"<<endl;
cout<<"\n"<<endl;
cout<<"*******"<<endl;
cout<<"*"<<endl;
cout<<"*"<<endl;
cout<<"* *****"<<endl;
cout<<"* *   *"<<endl;
cout<<"* *   *"<<endl;
cout<<"***   *"<<endl;
cout<<"\n"<<endl;
cout<<"*     *"<<endl;
cout<<"*     *"<<endl;
cout<<"*     *"<<endl;
cout<<"*******"<<endl;
cout<<"*     *"<<endl;
cout<<"*     *"<<endl;
cout<<"*     *"<<endl;
cout<<"\n"<<endl;
cout<<"*******"<<endl;
cout<<"   *"<<endl;
cout<<"   *"<<endl;
cout<<"   *"<<endl;
cout<<"   *"<<endl;
cout<<"   *"<<endl;
cout<<"********"<<endl;
cout<<"\n"<<endl;
cout<<"*******"<<endl;
cout<<"   *"<<endl;
cout<<"   *"<<endl;
cout<<"   *"<<endl;
cout<<"   *"<<endl;
cout<<"   *"<<endl;
cout<<"****"<<endl;
cout<<"\n"<<endl;
cout<<"*   *"<<endl;
cout<<"*  *"<<endl;
cout<<"* *"<<endl;
cout<<"**"<<endl;
cout<<"* *"<<endl;
cout<<"*  *"<<endl;
cout<<"*   *"<<endl;
cout<<"\n"<<endl;
cout<<"*"<<endl;
cout<<"*"<<endl;
cout<<"*"<<endl;
cout<<"*"<<endl;
cout<<"*"<<endl;
cout<<"*******"<<endl;
cout<<"\n"<<endl;
getch();
}               
