#include <iostream.h>
#include <conio.h>
void main()
{
clrscr();
int i;
int a;
int b;
int l;
int r;
int ba;
int h;
int s;
int s1;
int s2;
int d1;
int d2;
cout<<"                             AREAS OF PLANE FIGURES"<<endl;
cout<<" "<<endl;
cout<<"Choose from one of these shapes."<<endl;
cout<<" "<<endl;
cout<<"1 - Square"<<endl;
cout<<" "<<endl;
cout<<"2 - Rectangle"<<endl;
cout<<" "<<endl;
cout<<"3 - Circle"<<endl;
cout<<" "<<endl;
cout<<"4 - Triangle"<<endl;
cout<<" "<<endl;
cout<<"5 - Semicircle"<<endl;
cout<<" "<<endl;
cout<<"6 - Equilateral Triangle"<<endl;
cout<<" "<<endl;
cout<<"7 - Quadrant"<<endl;
cout<<" "<<endl;
cout<<"8 - Trapezium"<<endl;
cout<<" "<<endl;
cout<<"9 - Rhombus"<<endl;
cout<<" "<<endl;
cout<<"10 - Parallelogram"<<endl;
cout<<" "<<endl;  
cout<<"Choose from one of these numbers: "<<endl;
cin>>i;
cout<<" "<<endl;
switch(i)
{
case 1:cout<<"The formula of the area of a Square is a*a."<<endl;
cout<<"Choose the value of the side 'a': "<<endl;
cin>>a;
cout<<"Area of Square = ";
cout<<a*a;break;
case 2:cout<<"The formula of the area of a Rectangle is l*b."<<endl;
cout<<"Choose the value of the length 'l': "<<endl;
cin>>l;
cout<<"Choose the value of the breadth 'b': "<<endl;
cin>>b;
cout<<"Area of Rectangle = ";
cout<<l*b;break;
case 3:cout<<"The formula of the area of a Circle is pi*r*r."<<endl;
cout<<"The value of pi is 3.14."<<endl;
cout<<"Choose the value of the radius 'r': "<<endl;
cin>>r;
cout<<"Area of Circle = ";
cout<<3.14*r*r;break;
case 4:cout<<"The formula of the area of a Triangle is 1/2*h*ba."<<endl;
cout<<"Choose the value of the base 'ba': "<<endl;
cin>>ba;
cout<<"Choose the value of the height 'h': "<<endl;
cin>>h;
cout<<"Area of Triangle = ";
cout<<0.5*h*ba;break;
case 5:cout<<"The formula of the area of a Semicircle is 1/2*pi*r*r."<<endl;
cout<<"The value of pi is 3.14."<<endl;
cout<<"Choose the value of the radius 'r': "<<endl;
cin>>r;
cout<<"Area of Semicircle = ";
cout<<0.5*3.14*r*r;break;
case 6:cout<<"The formula of the area of an Equilateral Triangle is 1.73*s*s."<<endl;
cout<<"Choose the value of the side 's': "<<endl;
cin>>s;
cout<<"Area of Equilateral Triangle = ";
cout<<1.732*s*s;break;
case 7:cout<<"The formula of the area of a Quadrant is 1/4*pi*r*r."<<endl;
cout<<"The value of pi is 3.14."<<endl;
cout<<"Choose the value of the radius 'r': "<<endl;
cin>>r;
cout<<"Area of Quadrant = ";
cout<<0.25*3.14*r*r;break;
case 8:cout<<"The formula of the area of an Trapezium is 1/2*ba*h*(s1+s2)."<<endl;
cout<<"Choose the value of the side 's1': "<<endl;
cin>>s1;
cout<<"Choose the value of the side 's2': "<<endl;
cin>>s2;
cout<<"Choose the value of the base 'ba': "<<endl;
cin>>ba;
cout<<"Choose the value of the height 'h': "<<endl;
cin>>h;
cout<<"Area of Trapezium = ";
cout<<0.5*ba*h*(s1+s2);break;
case 9:cout<<"The formula of the area of a Rhombus is 1/2*d1*d2."<<endl;
cout<<"Choose the value of the diagonal 'd1': "<<endl;
cin>>d1;
cout<<"Choose the value of the diagonal 'd2': "<<endl;
cin>>d2;
cout<<"Area of Rhombus = ";
cout<<0.5*d1*d2;break;
case 10:cout<<"The formula of the area of a Parallelogram is h*ba."<<endl;
cout<<"Choose the value of the height 'h': "<<endl;
cin>>h;
cout<<"Choose the value of the base 'ba': "<<endl;
cin>>ba;
cout<<"Area of Parallelogram = ";
cout<<h*ba;break;
default:cout<<"Choose only one of the ten options";break;
}
getch();
}
