#include <iostream.h>
#include <conio.h>
void main()
{
clrscr();
int i;
cout<<"                              Elements and Symbols"<<endl;
cout<<" "<<endl;
cout<<"Choose the atomic number next to the element and find its symbol."<<endl;
cout<<" "<<endl;
cout<<"Hydrogen - 1"<<endl;
cout<<"Helium - 2"<<endl;
cout<<"Lithium - 3"<<endl;
cout<<"Beryllium - 4"<<endl;
cout<<"Boron - 5"<<endl;
cout<<"Carbon - 6"<<endl;
cout<<"Nitrogen - 7"<<endl;
cout<<"Oxygen - 8"<<endl;
cout<<"Fluorine - 9"<<endl;
cout<<"Neon - 10"<<endl;
cout<<"Sodium - 11"<<endl;
cout<<"Magnesium - 12"<<endl;
cout<<"Aluminium - 13"<<endl;
cout<<"Silicon - 14"<<endl;
cout<<"Phosphorous - 15"<<endl;
cout<<"Sulphur - 16"<<endl;
cout<<"Chlorine - 17"<<endl;
cout<<"Argon - 18"<<endl;
cout<<"Potassium - 19"<<endl;
cout<<"Calcium - 20"<<endl;
cout<<"Scandium - 21"<<endl;
cout<<"Titanium - 22"<<endl;
cout<<"Vanadium - 23"<<endl;
cout<<"Chromium - 24"<<endl;
cout<<"Manganese - 25"<<endl;
cout<<"Iron - 26"<<endl;
cout<<"Cobalt - 27"<<endl;
cout<<"Nickel - 28"<<endl;
cout<<"Copper - 29"<<endl;
cout<<"Zinc - 30"<<endl;
cout<<"Gallium - 31"<<endl;
cout<<"Germanium - 32"<<endl;
cout<<"Arsenic - 33"<<endl;
cout<<"Selenium - 34"<<endl;
cout<<"Bromine - 35"<<endl;
cout<<"Krypton - 36"<<endl;
cout<<"Rubidium - 37"<<endl;
cout<<"Strontium - 38"<<endl;
cout<<"Yttrium - 39"<<endl;
cout<<"Zirconium - 40"<<endl;
cout<<"Niobium - 41"<<endl;
cout<<"Molybdenum - 42"<<endl;
cout<<"Technetium - 43"<<endl;
cout<<"Ruthenium - 44"<<endl;
cout<<"Rhodium - 45"<<endl;
cout<<"Palladium - 46"<<endl;
cout<<"Silver - 47"<<endl;
cout<<"Cadmium - 48"<<endl;
cout<<"Indium - 49"<<endl;
cout<<"Tin - 50"<<endl;
cout<<"Antimony - 51"<<endl;
cout<<"Tellurium - 52"<<endl;
cout<<"Iodine - 53"<<endl;
cout<<"Xenon - 54"<<endl;
cout<<"Caesium - 55"<<endl;
cout<<"Barium - 56"<<endl;
cout<<"Lanthanum - 57"<<endl;
cout<<"Cerium - 58"<<endl;
cout<<"Praseodymium - 59"<<endl;
cout<<"Neodymium - 60"<<endl;
cout<<"Promethium - 61"<<endl;
cout<<"Samarium - 62"<<endl;
cout<<"Europium - 63"<<endl;
cout<<"Gadolinium - 64"<<endl;
cout<<"Terbium - 65"<<endl;
cout<<"Dysporsium - 66"<<endl;
cout<<"Holmium - 67"<<endl;
cout<<"Erbium - 68"<<endl;
cout<<"Thulium - 69"<<endl;
cout<<"Yttrbium - 70"<<endl;
cout<<"Lutetium - 71"<<endl;
cout<<"Hafnium - 72"<<endl;
cout<<"Tantalum - 73"<<endl;
cout<<"Tungsten - 74"<<endl;
cout<<"Rhenium - 75"<<endl;
cout<<"Osmium - 76"<<endl;
cout<<"Iridium - 77"<<endl;
cout<<"Platinum - 78"<<endl;
cout<<"Gold - 79"<<endl;
cout<<"Mercury - 80"<<endl;
cout<<"Thallium - 81"<<endl;
cout<<"Lead - 82"<<endl;
cout<<"Bismuth - 83"<<endl;
cout<<"Polonium - 84"<<endl;
cout<<"Astatine - 85"<<endl;
cout<<"Radon - 86"<<endl;
cout<<"Francium - 87"<<endl;
cout<<"Radium - 88"<<endl;
cout<<"Actinium - 89"<<endl;
cout<<"Thallium - 90"<<endl;
cout<<"Protactinium - 91"<<endl;
cout<<"Uranium - 92"<<endl;
cout<<"Neptunium - 93"<<endl;
cout<<"Plutonium - 94"<<endl;
cout<<"Americium - 95"<<endl;
cout<<"Curium - 96"<<endl;
cout<<"Berkelium - 97"<<endl;
cout<<"Californium - 98"<<endl;
cout<<"Einsteinium - 99"<<endl;
cout<<"Fermium - 100"<<endl;
cout<<"Mendelevium - 101"<<endl;
cout<<"Nobelium - 102"<<endl;
cout<<"Lawrencium - 103"<<endl;
cout<<"Rutherfordium - 104"<<endl;
cout<<"Dubnium - 105"<<endl;
cout<<"Seaborgium - 106"<<endl;
cout<<"Bohrium - 107"<<endl;
cout<<"Hassium - 108"<<endl;
cout<<"Meitnerium - 109"<<endl;
cout<<"Darmstatdium - 110"<<endl;
cout<<"Roentgenium - 111"<<endl;
cout<<"Ununbium - 112"<<endl;
cout<<"Ununtrium - 113"<<endl;
cout<<"Ununquadrium - 114"<<endl;
cout<<"Ununpentium - 115"<<endl;
cout<<"Ununhexium - 116"<<endl;
cout<<"Ununseptium - 117"<<endl;
cout<<"Ununoctium - 118"<<endl;
cout<<" "<<endl;
cout<<"Choose a number between 1 and 118 : ";
cin>>i;
cout<<" "<<endl;
switch(i)
{
case 1:cout<<"H";break;
case 2:cout<<"He";break;
case 3:cout<<"Li";break;
case 4:cout<<"Be";break;
case 5:cout<<"B";break;
case 6:cout<<"C";break;
case 7:cout<<"N";break;
case 8:cout<<"O";break;
case 9:cout<<"F";break;
case 10:cout<<"Ne";break;
case 11:cout<<"Na";break;
case 12:cout<<"Mg";break;
case 13:cout<<"Al";break;
case 14:cout<<"Si";break;
case 15:cout<<"P";break;
case 16:cout<<"S";break;
case 17:cout<<"Cl";break;
case 18:cout<<"Ar";break;
case 19:cout<<"K";break;
case 20:cout<<"Ca";break;
case 21:cout<<"Sc";break;
case 22:cout<<"Ti";break;
case 23:cout<<"V";break;
case 24:cout<<"Cr";break;
case 25:cout<<"Mn";break;
case 26:cout<<"Fe";break;
case 27:cout<<"Co";break;
case 28:cout<<"Ni";break;
case 29:cout<<"Cu";break;
case 30:cout<<"Zn";break;
case 31:cout<<"Ga";break;
case 32:cout<<"Ge";break;
case 33:cout<<"As";break;
case 34:cout<<"Se";break;
case 35:cout<<"Br";break;
case 36:cout<<"Kr";break;
case 37:cout<<"Rb";break;
case 38:cout<<"Sr";break;
case 39:cout<<"Y";break;
case 40:cout<<"Zr";break;
case 41:cout<<"Nb";break;
case 42:cout<<"Mo";break;
case 43:cout<<"Tc";break;
case 44:cout<<"Ru";break;
case 45:cout<<"Rh";break;
case 46:cout<<"Pd";break;
case 47:cout<<"Ag";break;
case 48:cout<<"Cd";break;
case 49:cout<<"In";break;
case 50:cout<<"Sn";break;
case 51:cout<<"Sb";break;
case 52:cout<<"Te";break;
case 53:cout<<"I";break;
case 54:cout<<"Xe";break;
case 55:cout<<"Cs";break;
case 56:cout<<"Ba";break;
case 57:cout<<"La";break;
case 58:cout<<"Ce";break;
case 59:cout<<"Pr";break;
case 60:cout<<"Nd";break;
case 61:cout<<"Pm";break;
case 62:cout<<"Sm";break;
case 63:cout<<"Eu";break;
case 64:cout<<"Gd";break;
case 65:cout<<"Tb";break;
case 66:cout<<"Dy";break;
case 67:cout<<"Ho";break;
case 68:cout<<"Er";break;
case 69:cout<<"Tm";break;
case 70:cout<<"Yb";break;
case 71:cout<<"Lu";break;
case 72:cout<<"Hf";break;
case 73:cout<<"Ta";break;
case 74:cout<<"W";break;
case 75:cout<<"Re";break;
case 76:cout<<"Os";break;
case 77:cout<<"Ir";break;
case 78:cout<<"Pt";break;
case 79:cout<<"Au";break;
case 80:cout<<"Hg";break;
case 81:cout<<"Tl";break;
case 82:cout<<"Pb";break;
case 83:cout<<"Bi";break;
case 84:cout<<"Po";break;
case 85:cout<<"At";break;
case 86:cout<<"Rn";break;
case 87:cout<<"Fr";break;
case 88:cout<<"Ra";break;
case 89:cout<<"Ac";break;
case 90:cout<<"Th";break;
case 91:cout<<"Pa";break;
case 92:cout<<"U";break;
case 93:cout<<"Np";break;
case 94:cout<<"Pu";break;
case 95:cout<<"Am";break;
case 96:cout<<"Cm";break;
case 97:cout<<"Bk";break;
case 98:cout<<"Cf";break;
case 99:cout<<"Es";break;
case 100:cout<<"Fm";break;
case 101:cout<<"Md";break;
case 102:cout<<"No";break;
case 103:cout<<"Lr";break;
case 104:cout<<"Rf";break;
case 105:cout<<"Db";break;
case 106:cout<<"Sg";break;
case 107:cout<<"Bh";break;
case 108:cout<<"Hs";break;
case 109:cout<<"Mt";break;
case 110:cout<<"Ds";break;
case 111:cout<<"Rg";break;
case 112:cout<<"Uub";break;
case 113:cout<<"Uut";break;
case 114:cout<<"Uuq";break;
case 115:cout<<"Uup";break;
case 116:cout<<"Uuh";break;
case 117:cout<<"Uus";break;
case 118:cout<<"Uuo";break;
default:cout<<"Choose numbers only from 1 to 118."<<endl;
}
getch();
}
